#!/bin/bash

nohup sudo rsync -aAXv --delete /* /media/extdrive/linux/deepthought1 --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,/home/*/.gvfs,/media/*} > `mktemp` &>/dev/null
