#!/bin/bash

max=`wc -l /etc/dictionaries-common/words | grep -Eo "[0-9]+"`
searchStr=""
x=`bashcalc $1*$2`
y=`bashcalc $2*$3`
z=`bashcalc $3*$1`
echo $x
echo $y
echo $z
if [ "$x" -lt "$max" ];
then
	searchStr="$searchStr `head -"$x" /etc/dictionaries-common/words | tail -1`"
fi
if [ "$y" -lt "$max" ];
then
	searchStr="$searchStr `head -"$y" /etc/dictionaries-common/words | tail -1`"
fi
if [ "$z" -lt "$max" ];
then
	searchStr="$searchStr `head -"$z" /etc/dictionaries-common/words | tail -1`"
fi
echo $searchStr
