#!/bin/bash

max=`wc -l /etc/dictionaries-common/words | grep -Eo "[0-9]+"`
searchStr=""
arg1=$1
arg2=$2
arg3=$3
if [ "$arg1" -lt "$max" ];
then
	searchStr="$searchStr `head -"$arg1" /etc/dictionaries-common/words | tail -1`"
fi
if [ "$arg2" -lt "$max" ];
then
	searchStr="$searchStr `head -"$arg2" /etc/dictionaries-common/words | tail -1`"
fi
if [ "$arg3" -lt "$max" ];
then
	searchStr="$searchStr `head -"$arg3" /etc/dictionaries-common/words | tail -1`"
fi
echo $searchStr
